### ISSUE TITLE
关于图像结果可视化问题

### ISSUE THREAD

**Issue by rw1995** [dlyldxwl/fssd.pytorch#1]
请问大佬，我看了您的csdn，所以慕名前来。但是我想尝试图像结果可视化，不知道如何写，请问大佬能不能提供思路帮助下我，刚上路，感觉还是看着图片可视化来的舒服，望交流回复

**Comment by dlyldxwl** [comment]
@rw1995 
I am sry I see that until now ..)
You only need obtain the output of the layer you want visualization, then select one channel of the output to show, certainly, I suggest you apply matplotlib to show the feature rather than cv2~

**Comment by rw1995** [comment]
thank you~~~~~
