### ISSUE TITLE
any plans to add support for focal loss? (instead of ohem)

### ISSUE THREAD

**Issue by zhanghengdev** [dlyldxwl/fssd.pytorch#6]
Dear @dlyldxwl ,
Great work! have you ever tried focal loss in FSSD? It seems to be better than ohem in your programme.

Following repos might help: 
https://github.com/marvis/pytorch-yolo2/blob/master/FocalLoss.py
https://github.com/yhenon/pytorch-retinanet/blob/master/losses.py

I have tried myself, but it seems to be worse than ohem...

Best regards,

**Comment by dlyldxwl** [comment]
Yes, but not this repo, I will release a project after 1-2 weeks about stronger one-stage detector based on ssd and yolo v3, which integrate much tricks, e.g., mix up, GIOU, focal loss and  so on. If you are interested in it, please give more attention.

**Comment by zhanghengdev** [comment]
Great!

**Comment by dlyldxwl** [comment]
@ZHANGHeng19931123 
Hello~
When I apply label smooth to SSD, mAP drops ~1 point. 
I think this is because background class produces negative impact, thus I ingore it, but also not work.
Have you tried it?

**Comment by zhanghengdev** [comment]
Sorry, I have never tried label smooth...
